name: Moengage Acquisition leads push all

on:
  schedule:
  # # 5:02 AM IST = 11:32 PM UTC (IST is UTC+5:30) daily
    - cron: '32 23 * * *'
  workflow_dispatch:
    inputs:
      cycle_day_override:
        description: 'Override Cycle Day (0 to 10)'
        required: false
        default: ''
      push_current_month_override:
        description: 'Override Push Current Month (true/false)'
        required: false
        default: ''

jobs:
  push-leads:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          MOENGAGE_WORKSPACE_ID: ${{ secrets.MOENGAGE_WORKSPACE_ID }}
          MOENGAGE_API_KEY: ${{ secrets.MOENGAGE_API_KEY }}
          CYCLE_DAY: ${{ github.event.inputs.cycle_day_override }}
          PUSH_CURRENT_MONTH: ${{ github.event.inputs.push_current_month_override }}
        run: python moengage_acquisition_leads_push_all.py
